permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: pygments

kramdown:
  input: GFM

# 作者信息
author: 
  name: 落风
  email: luofenglc@gmail.com
  link: http://www.liuschen.com

# 站点信息
title: 落风的博客 
description: 落风的博客
url: http://www.liuschen.com
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://7xpui7.com1.z0.glb.clouddn.com/blog-site-avatar.png
favicon: http://7xpui7.com1.z0.glb.clouddn.com/blog-site-favicon.ico

# disqus 设置
disqus:
  shortname: luofeng